#!/bin/bash
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=100 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=500 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=A --batch_size=1000 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=100 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=500 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=B --batch_size=1000 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=50 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=50 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=50 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=100 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=500 --num_epoch=100 --p_dropout=0.5
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=100 --p_dropout=0.1
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=100 --p_dropout=0.3
ipython3 4.entrenar_red.py -- --dataset='dataset.csv' --modelo=C --batch_size=1000 --num_epoch=100 --p_dropout=0.5
